# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hloth/Documents/session-messenger-watchos/LibSession-Util

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hloth/Documents/session-messenger-watchos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"libprotobuf\" \"libprotobuf-lite\" \"protobuf-export\" \"protobuf-headers\" \"protobuf-protos\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hloth/Documents/session-messenger-watchos/CMakeFiles /Users/hloth/Documents/session-messenger-watchos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hloth/Documents/session-messenger-watchos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gmp_external

# Build rule for target.
gmp_external: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmp_external
.PHONY : gmp_external

# fast build rule for target.
gmp_external/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmp_external.dir/build.make CMakeFiles/gmp_external.dir/build
.PHONY : gmp_external/fast

#=============================================================================
# Target rules for targets named nettle_external

# Build rule for target.
nettle_external: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nettle_external
.PHONY : nettle_external

# fast build rule for target.
nettle_external/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nettle_external.dir/build.make CMakeFiles/nettle_external.dir/build
.PHONY : nettle_external/fast

#=============================================================================
# Target rules for targets named sodium-internal

# Build rule for target.
sodium-internal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sodium-internal
.PHONY : sodium-internal

# fast build rule for target.
sodium-internal/fast:
	$(MAKE) $(MAKESILENT) -f external/libsodium-internal/CMakeFiles/sodium-internal.dir/build.make external/libsodium-internal/CMakeFiles/sodium-internal.dir/build
.PHONY : sodium-internal/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f external/zstd/build/cmake/CMakeFiles/clean-all.dir/build.make external/zstd/build/cmake/CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named libzstd_static

# Build rule for target.
libzstd_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libzstd_static
.PHONY : libzstd_static

# fast build rule for target.
libzstd_static/fast:
	$(MAKE) $(MAKESILENT) -f external/zstd/build/cmake/lib/CMakeFiles/libzstd_static.dir/build.make external/zstd/build/cmake/lib/CMakeFiles/libzstd_static.dir/build
.PHONY : libzstd_static/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f external/zstd/build/cmake/lib/CMakeFiles/uninstall.dir/build.make external/zstd/build/cmake/lib/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named crypto

# Build rule for target.
crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypto
.PHONY : crypto

# fast build rule for target.
crypto/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/crypto.dir/build.make src/CMakeFiles/crypto.dir/build
.PHONY : crypto/fast

#=============================================================================
# Target rules for targets named config

# Build rule for target.
config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 config
.PHONY : config

# fast build rule for target.
config/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/config.dir/build.make src/CMakeFiles/config.dir/build
.PHONY : config/fast

#=============================================================================
# Target rules for targets named onionreq

# Build rule for target.
onionreq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 onionreq
.PHONY : onionreq

# fast build rule for target.
onionreq/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/onionreq.dir/build.make src/CMakeFiles/onionreq.dir/build
.PHONY : onionreq/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/version.dir/build.make src/CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named protos

# Build rule for target.
protos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 protos
.PHONY : protos

# fast build rule for target.
protos/fast:
	$(MAKE) $(MAKESILENT) -f proto/CMakeFiles/protos.dir/build.make proto/CMakeFiles/protos.dir/build
.PHONY : protos/fast

#=============================================================================
# Target rules for targets named regen-protobuf

# Build rule for target.
regen-protobuf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 regen-protobuf
.PHONY : regen-protobuf

# fast build rule for target.
regen-protobuf/fast:
	$(MAKE) $(MAKESILENT) -f proto/CMakeFiles/regen-protobuf.dir/build.make proto/CMakeFiles/regen-protobuf.dir/build
.PHONY : regen-protobuf/fast

#=============================================================================
# Target rules for targets named libprotobuf-lite

# Build rule for target.
libprotobuf-lite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libprotobuf-lite
.PHONY : libprotobuf-lite

# fast build rule for target.
libprotobuf-lite/fast:
	$(MAKE) $(MAKESILENT) -f _deps/protobuf-build/CMakeFiles/libprotobuf-lite.dir/build.make _deps/protobuf-build/CMakeFiles/libprotobuf-lite.dir/build
.PHONY : libprotobuf-lite/fast

#=============================================================================
# Target rules for targets named libprotobuf

# Build rule for target.
libprotobuf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libprotobuf
.PHONY : libprotobuf

# fast build rule for target.
libprotobuf/fast:
	$(MAKE) $(MAKESILENT) -f _deps/protobuf-build/CMakeFiles/libprotobuf.dir/build.make _deps/protobuf-build/CMakeFiles/libprotobuf.dir/build
.PHONY : libprotobuf/fast

#=============================================================================
# Target rules for targets named testAll

# Build rule for target.
testAll: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testAll
.PHONY : testAll

# fast build rule for target.
testAll/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/testAll.dir/build.make tests/CMakeFiles/testAll.dir/build
.PHONY : testAll/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/check.dir/build.make tests/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named swarm-auth-test

# Build rule for target.
swarm-auth-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 swarm-auth-test
.PHONY : swarm-auth-test

# fast build rule for target.
swarm-auth-test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/swarm-auth-test.dir/build.make tests/CMakeFiles/swarm-auth-test.dir/build
.PHONY : swarm-auth-test/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f tests/Catch2/src/CMakeFiles/Catch2.dir/build.make tests/Catch2/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f tests/Catch2/src/CMakeFiles/Catch2WithMain.dir/build.make tests/Catch2/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... check"
	@echo "... clean-all"
	@echo "... gmp_external"
	@echo "... nettle_external"
	@echo "... regen-protobuf"
	@echo "... uninstall"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... config"
	@echo "... crypto"
	@echo "... libprotobuf"
	@echo "... libprotobuf-lite"
	@echo "... libzstd_static"
	@echo "... onionreq"
	@echo "... protos"
	@echo "... sodium-internal"
	@echo "... swarm-auth-test"
	@echo "... testAll"
	@echo "... version"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

